### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "first_name": "Swan Htet",
  "last_name": "Aung Phyo",
  "email": "swanhtetaungp@gmail.com",
  "password": "securePassword123",
  "role_name": "user",
  "age": 25
}
### Verify email
POST {{baseUrl}}/auth/verify
Content-Type: application/json

{
  "code": "029293",
  "email": "swanhtetaungp@gmail.com"
}
### Login with credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "swanhtetaungp@gmail.com",
  "password": "securePassword123"
}

###
GET {{baseUrl}}/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY4MDI2OTMsImlhdCI6MTc0NjgwMDg5Mywicm9sZSI6InVzZXIiLCJzdWIiOiI4ZTJkMTc2ZS1lMGM3LTRkMzYtYTgxMC02ZTljZWEzYjY5OTQiLCJ0eXBlIjowfQ.FSPbbg1T5sEgocXZodGruyes84Mh4VUFTrP9JXbJ90g


### Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY4MDI3NTgsImlhdCI6MTc0NjgwMDk1OCwicm9sZSI6InVzZXIiLCJzdWIiOiI4ZTJkMTc2ZS1lMGM3LTRkMzYtYTgxMC02ZTljZWEzYjY5OTQiLCJ0eXBlIjowfQ.j36vh15NGiT7hnDdO73dxlaJ9i31js-UBCiVJjZcJow
### Try to get user private data with admin token
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY4MDI3NTgsImlhdCI6MTc0NjgwMDk1OCwicm9sZSI6InVzZXIiLCJzdWIiOiI4ZTJkMTc2ZS1lMGM3LTRkMzYtYTgxMC02ZTljZWEzYjY5OTQiLCJ0eXBlIjowfQ.j36vh15NGiT7hnDdO73dxlaJ9i31js-UBCiVJjZcJow
### Try to get admin private data with user token
GET {{baseUrl}}/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY4MDI2OTMsImlhdCI6MTc0NjgwMDg5Mywicm9sZSI6InVzZXIiLCJzdWIiOiI4ZTJkMTc2ZS1lMGM3LTRkMzYtYTgxMC02ZTljZWEzYjY5OTQiLCJ0eXBlIjowfQ.FSPbbg1T5sEgocXZodGruyes84Mh4VUFTrP9JXbJ90g

