### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "first_name": "Swan Htet",
  "last_name": "Aung Phyo",
  "email": "swanhtetaungp@gmail.com",
  "password": "securePassword123",
  "role_name": "user",
  "age": 25
}
### Verify email
POST {{baseUrl}}/auth/verify
Content-Type: application/json

{
  "code": "046416",
  "email": "swanhtetaungp@gmail.com"
}
### Login with credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "swanhtetaungp@gmail.com",
  "password": "securePassword123"
}

###
GET {{baseUrl}}/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY3OTE3MDUsImlhdCI6MTc0Njc4OTkwNSwicm9sZSI6InVzZXIiLCJzdWIiOiIzZGFjNmVkYS1lN2NmLTQwN2UtODI4MS0wNmNmNGM2NGI1NTIiLCJ0eXBlIjowfQ.jmbOmRCL5OtjCMF6GMEHL6IcjNmKHwE4SLqKF6mJvEQ

### Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY3OTI0MjcsImlhdCI6MTc0Njc5MDYyNywicm9sZSI6InVzZXIiLCJzdWIiOiJlY2FlYTRmZC1mNmViLTQwZTYtYjMzZC0yZjhmNzUzMzYzMGQiLCJ0eXBlIjowfQ.Ppbgprw4TEwrH17frHTxH5JISyzB-JuQW3Q_0zljrdY
### Try to get user private data with admin token
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY3OTE3MDUsImlhdCI6MTc0Njc4OTkwNSwicm9sZSI6InVzZXIiLCJzdWIiOiIzZGFjNmVkYS1lN2NmLTQwN2UtODI4MS0wNmNmNGM2NGI1NTIiLCJ0eXBlIjowfQ.jmbOmRCL5OtjCMF6GMEHL6IcjNmKHwE4SLqKF6mJvEQ
### Try to get admin private data with user token
GET {{baseUrl}}/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY3OTE3MDUsImlhdCI6MTc0Njc4OTkwNSwicm9sZSI6InVzZXIiLCJzdWIiOiIzZGFjNmVkYS1lN2NmLTQwN2UtODI4MS0wNmNmNGM2NGI1NTIiLCJ0eXBlIjowfQ.jmbOmRCL5OtjCMF6GMEHL6IcjNmKHwE4SLqKF6mJvEQ