

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend_net

#  go-api:
#    build: .
#    container_name: golang-api
#    restart: unless-stopped
#    environment:
#      PORT: 8081
#      SSL_CERT_FILE: /certs/server.crt
#      SSL_KEY_FILE: /certs/server.key
#      DATABASE_URL_DNS: postgresql://postgres:postgres@postgres:5432/postgres
#      REDIS_ADDRESS: redis:6379
#      REDIS_PASSWORD: SWAN
#      APP_IDLE_TIMEOUT: 60s
#      APP_READ_TIMEOUT: 10s
#      APP_WRITE_TIMEOUT: 10s
#      RES_API_KEY: re_9jUsKjRx_LGLEWtsr1USfy8bJQkXchW16
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./cmd/server/certs:/certs
#      - .:/app
#    networks:
#      - backend_net
#    depends_on:
#      - postgres
#      - redis



volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
